insurance:
  head: 2
  learning_rate: 2e-4
  ssl_reg_weight: 1
lastfm-1k:
  head: 4
  learning_rate: 2e-4
  ssl_reg_weight: 1
ml-1m:
rent_the_runway:
  head: 2
  learning_rate: 1e-4
  ssl_reg_weight: 1
tafeng:
