# 'USER_ID_FIELD': user_id,
ITEM_ID_FIELD: venue_id
TIME_FIELD: timestamp
train_batch_size: 4096
eval_batch_size: 500000
load_col: {'inter': ['user_id', 'venue_id', 'timestamp']}
unused_col: {'inter': ['timestamp']}

# NCL
num_clusters: 140
